    .include "asm/head.inc"

    .section "fake_glue", "ax"

    @ this section should be generated by the linker, but modern ld won't generating matching veneers
    @ (specifically: the padding nop is replaced by another instruction).

    .global ClearOam_thm
    .type ClearOam_thm, function

    .thumb
ClearOam_thm:
    bx pc
    nop
    .arm
    b ClearOam

    .size Checksum32_thm, . - Checksum32_thm

    .global Checksum32_thm
    .type Checksum32_thm, function

    .thumb
Checksum32_thm:
    bx pc
    nop
    .arm
    b Checksum32

    .size Checksum32_thm, . - Checksum32_thm
