# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

.SUFFIXES:

TARGET := embed
SOURCES := embed.c

CC := gcc
CFLAGS := -Og -g -Wall -Wextra

$(TARGET): $(SOURCES)
	$(CC) $(CFLAGS) -o $(TARGET) $(SOURCES)
